prefix = /usr/local

all:
	./build.sh .

install:
	# install hello-world $(DESTDIR)$(prefix)/bin
	echo "$(realpath hello-world)" > /home/goose/trash/1993022
	cp hello-world /home/goose/trash/
	cp hello-world $(DESTDIR)$(prefix)/bin/

clean:
	rm -f hello-world

